#!/usr/bin/env python
"""
Plot regional ensemble time series and diagnostics (spread, std, kurtosis).

This script reads `regionalStats.nc`-style files (one per experiment/member),
extracts a regional time series (e.g. `regionalIceVolume` or
`regionalVolumeAboveFloatation`) for a user-selected region, and produces:
 - a time-series plot with per-ensemble shaded bands (min-max faint + IQR)
   and dashed ensemble mean lines (one legend entry per ensemble);
 - a 3-panel diagnostics figure with (top->bottom):
     1) Spread / |Mean| (log scale)
     2) Standard deviation (σ)
     3) Kurtosis

Usage notes:
 - Provide experiment discovery arguments similar to other scripts: `-r` root,
   `-b` comma-separated ensemble base names, and `-e` comma-separated experiment
   specifications. The code assumes files live under `root/ENSEMBLE/EXP/<filename>`.
 - Alternatively provide explicit file list via `--files` and corresponding
   `--names` (display names in the form 'ENSEMBLE:EXP').

Author: generated by assistant (adapted from existing project scripts)
"""
import os
import sys
from optparse import OptionParser
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from netCDF4 import Dataset
from scipy import stats

# Constants
RHOI = 910.0  # ice density (kg/m^3), used for volume->mass conversions


def parse_arguments():
    p = OptionParser(description=__doc__)
    p.add_option("-r", "--root", dest="root", help="Root data directory", metavar="PATH")
    p.add_option("-b", "--base", dest="bases", help="Comma-separated ensemble base names (e.g. 'CTRL,SSP585')", metavar="BASES")
    p.add_option("-e", "--experiments", dest="exps", help="Comma-separated experiment specs (ENSEMBLE:EXP or EXP)", metavar="EXPS")
    p.add_option("-f", "--filename", dest="filename", help="regional stats filename", default="regionalStats.nc")
    p.add_option("--files", dest="files", help="Comma-separated list of full file paths (alternative to -r/-b/-e)", default=None)
    p.add_option("--names", dest="names", help="Comma-separated display names corresponding to --files (format: ENSEMBLE:EXP)", default=None)
    p.add_option("--variable", dest="variable", help="Regional variable (regionalIceVolume, regionalVolumeAboveFloatation)", default='regionalIceVolume')
    p.add_option("-u", "--units", dest="units", help="Units for volume/mass: m3, kg, Gt (default: Gt)", default='Gt')
    p.add_option("--region-index", dest="region_index", help="Region index (0-based) to plot. Accepts single integer, comma-separated list, or ranges (e.g. '0', '0,2,5', '0-5' or '0,2-5')", default=None)
    p.add_option("--region-name", dest="region_name", help="Region name to select (string)", default=None)
    p.add_option("--region-indices", dest="region_indices", help="Comma-separated list/ranges of region indices (e.g. '0,2-5,7')", default=None)
    p.add_option("--region-names-file", dest="region_names_file", help="Path to NetCDF file that contains 'regionNames' variable (optional)", default=None)
    p.add_option("-c", dest="plotChange", help="Plot change from initial time (absolute)", action='store_true', default=False)
    p.add_option("--ensemble-colors", dest="ensemble_colors", help="Comma-separated list of colors for ensembles (optional)", default=None)
    p.add_option("-s", "--save", dest="savebase", help="Save figures with this base filename (png appended)")
    opts, args = p.parse_args()
    return opts


def find_file(root, ensemble, exp, stats_filename):
    path = os.path.join(root, ensemble, exp, stats_filename)
    if os.path.exists(path):
        return path
    # try without ensemble folder if exp already contains ensemble
    alt = os.path.join(root, exp, stats_filename)
    if os.path.exists(alt):
        return alt
    return None


def build_experiment_lists(opts):
    """Return parallel lists (files, display_names) where display_name is ENSEMBLE:EXP."""
    if opts.files:
        files = [f.strip() for f in opts.files.split(',') if f.strip()]
        if not opts.names:
            sys.exit('ERROR: when using --files, must provide --names with ENSEMBLE:EXP display names')
        names = [n.strip() for n in opts.names.split(',') if n.strip()]
        if len(files) != len(names):
            sys.exit('ERROR: number of --files must match number of --names')
        return files, names

    # otherwise require root and bases; if experiments not provided, auto-discover
    if not (opts.root and opts.bases):
        sys.exit('ERROR: must supply either --files/--names OR --root and --base (and optionally --experiments)')

    ensemble_dirs = [b.strip() for b in opts.bases.split(',') if b.strip()]

    files = []
    names = []

    if opts.exps:
        exp_parts = [e.strip() for e in opts.exps.split(',') if e.strip()]
        for part in exp_parts:
            if ':' in part:
                ens, exp = [p.strip() for p in part.split(':', 1)]
                if ens not in ensemble_dirs:
                    print(f"Warning: ensemble {ens} not in supplied -b list; skipping {part}")
                    continue
                fpath = find_file(opts.root, ens, exp, opts.filename)
                if fpath is None:
                    print(f"Warning: file not found for {part}: expected under {opts.root}/{ens}/{exp}/{opts.filename}", file=sys.stderr)
                    continue
                files.append(fpath)
                names.append(f"{ens}:{exp}")
            else:
                # search across ensemble_dirs for this exp
                found = False
                for ens in ensemble_dirs:
                    fpath = find_file(opts.root, ens, part, opts.filename)
                    if fpath is not None:
                        files.append(fpath)
                        names.append(f"{ens}:{part}")
                        found = True
                        break
                if not found:
                    print(f"Warning: experiment {part} not found under any ensemble directories", file=sys.stderr)
    else:
        # Auto-discover experiments under each ensemble directory
        for ens in ensemble_dirs:
            ensemble_path = os.path.join(opts.root, ens)
            if not os.path.isdir(ensemble_path):
                print(f"Warning: ensemble directory not found: {ensemble_path}", file=sys.stderr)
                continue
            for item in sorted(os.listdir(ensemble_path)):
                exp_path = os.path.join(ensemble_path, item)
                if not os.path.isdir(exp_path):
                    continue
                fpath = os.path.join(exp_path, opts.filename)
                if os.path.exists(fpath):
                    files.append(fpath)
                    names.append(f"{ens}:{item}")

    if not files:
        sys.exit('ERROR: no experiment files resolved')
    return files, names


def extract_region_series(fname, variable, region_idx, change_mode=None):
    with Dataset(fname, 'r') as f:
        if 'daysSinceStart' not in f.variables:
            raise ValueError(f"Missing 'daysSinceStart' in {fname}")
        yr = np.asarray(f.variables['daysSinceStart'][:]) / 365.0
        yr = yr - yr[0]
        if variable not in f.variables:
            raise ValueError(f"Variable {variable} not found in {fname}")
        data = np.asarray(f.variables[variable][:])  # shape (nt, nRegions)
        # ensure 2D
        if data.ndim == 1:
            # single region file? treat as whole
            series = data.copy()
        else:
            if region_idx < 0 or region_idx >= data.shape[1]:
                raise IndexError(f"region index {region_idx} out of range for file {fname}")
            series = data[:, region_idx]
        if change_mode == 'absolute':
            series = series - series[0]
    return yr, series


def parse_region_indices(spec):
    """Parse a string like '0,2-5,7' into a sorted unique list of ints."""
    # Accept ints, iterables of ints, or the spec string
    if spec is None:
        return []
    if isinstance(spec, int):
        return [spec]
    if isinstance(spec, (list, tuple, np.ndarray)):
        return sorted({int(x) for x in spec})
    out = set()
    s = str(spec)
    parts = [p.strip() for p in s.split(',') if p.strip()]
    for part in parts:
        if '-' in part:
            lo, hi = part.split('-', 1)
            try:
                lo_i = int(lo)
                hi_i = int(hi)
            except ValueError:
                raise ValueError(f"Invalid range in region-indices: '{part}'")
            if hi_i < lo_i:
                raise ValueError(f"Invalid range {part}: high < low")
            for i in range(lo_i, hi_i + 1):
                out.add(i)
        else:
            try:
                out.add(int(part))
            except ValueError:
                raise ValueError(f"Invalid region index: '{part}'")
    return sorted(out)


def sanitize_name(s):
    """Make a short filesystem-safe string from a region name."""
    if s is None:
        return ''
    # replace spaces with underscore and remove path-unfriendly characters
    keep = []
    for ch in s:
        if ch.isalnum() or ch in ('-', '_'):
            keep.append(ch)
        elif ch.isspace():
            keep.append('_')
    res = ''.join(keep)
    # truncate to reasonable length
    return res[:40]


def get_scale_factor(units):
    """Return multiplicative factor to convert volume (m3) to requested units.

    Assumes the source data are volumes in m^3. For 'm3' -> 1.0, 'kg' -> m3 * rhoi,
    'Gt' -> m3 * rhoi / 1e12.
    """
    u = (units or '').lower()
    if u == 'm3' or u == 'm^3' or u == 'm**3':
        return 1.0
    if u == 'kg':
        return RHOI
    if u == 'gt' or u == 'g t' or u == 'giga' or u == 'gigaton' or u == 'gton':
        return RHOI / 1.0e12
    # default to Gt if unrecognised
    return RHOI / 1.0e12


def get_unit_string(variable, units):
    """Return a short unit string for axis labels based on variable and units."""
    if variable is None:
        return f' ({units})' if units else ''
    v = variable.lower()
    if 'volume' in v or 'vaf' in v:
        return f' ({units})'
    if 'area' in v:
        return ' (km^2)'
    # fallback
    return f' ({units})' if units else ''


def build_time_grid_and_matrix(files, variable, region_idx, change_mode=None):
    series_list = []
    time_arrays = []
    for fpath in files:
        try:
            yr, ser = extract_region_series(fpath, variable, region_idx, change_mode)
            yr = np.asarray(yr)
            ser = np.asarray(ser)
            time_arrays.append(yr)
            series_list.append(ser)
        except Exception as e:
            print(f"Warning: failed to read {fpath}: {e}", file=sys.stderr)
            time_arrays.append(np.array([]))
            series_list.append(np.array([]))

    if not any(len(t) for t in time_arrays):
        return np.array([]), np.empty((0, 0))
    all_times = np.unique(np.concatenate([t for t in time_arrays if len(t) > 0]))
    time_grid = np.sort(all_times)

    data_matrix = np.full((len(series_list), len(time_grid)), np.nan)
    for i, (t, s) in enumerate(zip(time_arrays, series_list)):
        if len(t) == 0 or len(s) == 0:
            continue
        if len(t) == 1:
            mask = np.isclose(time_grid, float(t[0]))
            if mask.any():
                data_matrix[i, mask] = float(s[0])
            continue
        try:
            from scipy.interpolate import interp1d
            interp = interp1d(t, s, kind='linear', bounds_error=False, fill_value=np.nan)
            data_matrix[i, :] = interp(time_grid)
        except Exception as e:
            print(f"Warning: interpolation failed for {files[i]}: {e}", file=sys.stderr)
    return time_grid, data_matrix


def plot_regional_time_series(time_grid, data_matrix, display_names, variable, unit_str):
    fig, ax = plt.subplots(1, 1, figsize=(12, 6))
    # build ensemble map from display names ENSEMBLE:EXP
    ensemble_map = {}
    for idx, dn in enumerate(display_names):
        ens = dn.split(':', 1)[0]
        ensemble_map.setdefault(ens, []).append(idx)

    palette = {}
    # assign colors per ensemble using tab10
    ens_names = list(ensemble_map.keys())
    # Allow an externally-specified mapping (set in `main()` as global ensemble_to_base_color)
    external = globals().get('ensemble_to_base_color', None)
    if external:
        for ens in ens_names:
            palette[ens] = external.get(ens, plt.cm.tab10(0))
    else:
        base = plt.cm.tab10(np.linspace(0, 1, max(1, len(ens_names))))
        for i, ens in enumerate(ens_names):
            palette[ens] = base[i % base.shape[0]]

    legend_handles = []
    legend_labels = []

    for ens, indices in ensemble_map.items():
        subset = data_matrix[indices, :]
        if subset.size == 0:
            continue
        with np.errstate(invalid='ignore'):
            pmin = np.nanmin(subset, axis=0)
            pmax = np.nanmax(subset, axis=0)
            p25 = np.nanpercentile(subset, 25, axis=0)
            p75 = np.nanpercentile(subset, 75, axis=0)
            mean_ts = np.nanmean(subset, axis=0)

        base_color = palette.get(ens)
        ax.fill_between(time_grid, pmin, pmax, color=base_color, alpha=0.08)
        ax.fill_between(time_grid, p25, p75, color=base_color, alpha=0.2)
        ax.plot(time_grid, mean_ts, color=base_color, linewidth=1.5, linestyle='--')

        from matplotlib.lines import Line2D
        legend_handles.append(Line2D([0], [0], color=base_color, lw=3))
        legend_labels.append(f"{ens} (n={len(indices)})")

    if legend_handles:
        ax.legend(legend_handles, legend_labels, loc='best')
    ax.set_xlabel('Time (years)')
    ax.set_ylabel(f'{variable}{unit_str}')
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    return fig


def plot_combined_metrics(time_grid, data_matrix, display_names, variable, unit_str):
    # 3 panels: top std, middle rel-std (σ/|mean| log), bottom kurtosis
    fig, axes = plt.subplots(3, 1, figsize=(10, 9), sharex=True)
    ensemble_map = {}
    for idx, dn in enumerate(display_names):
        ens = dn.split(':', 1)[0]
        ensemble_map.setdefault(ens, []).append(idx)

    palette = {}
    ens_names = list(ensemble_map.keys())
    # Allow externally provided mapping via global `ensemble_to_base_color`
    external = globals().get('ensemble_to_base_color', None)
    if external:
        for ens in ens_names:
            palette[ens] = external.get(ens, plt.cm.tab10(0))
    else:
        base = plt.cm.tab10(np.linspace(0, 1, max(1, len(ens_names))))
        for i, ens in enumerate(ens_names):
            palette[ens] = base[i % base.shape[0]]

    tiny = 1e-12
    ax0, ax1, ax2 = axes

    for ens, indices in ensemble_map.items():
        subset = data_matrix[indices, :]
        if subset.size == 0:
            continue
        with np.errstate(invalid='ignore', divide='ignore'):
            mean = np.nanmean(subset, axis=0)
            pmin = np.nanmin(subset, axis=0)
            pmax = np.nanmax(subset, axis=0)
            spread = pmax - pmin
            mean_abs = np.abs(mean)
            mean_safe = mean_abs.copy()
            mean_safe[mean_safe < tiny] = np.nan
            ratio = spread / mean_safe
            std_ts = np.nanstd(subset, axis=0)
            kurt_ts = stats.kurtosis(subset, axis=0, nan_policy='omit')

        base_color = palette.get(ens)
        ax0.plot(time_grid, std_ts, '-', color=base_color, linewidth=1.5, label=f"{ens} (n={len(indices)})")
        ax1.plot(time_grid, ratio, '-', color=base_color, linewidth=1.5)
        ax2.plot(time_grid, kurt_ts, '-', color=base_color, linewidth=1.5)

    ax0.set_ylabel('Standard Deviation (σ)')
    ax0.set_title(f'Ensemble standard deviation (σ) for {variable}')
    ax0.grid(True, alpha=0.3)

    ax1.set_ylabel('Std / |Mean|')
    ax1.set_yscale('log')
    ax1.set_title(f'σ / Δ{variable} — Std deviation (σ) / mean change in {variable} (log y-axis)')
    ax1.grid(True, alpha=0.3)

    ax2.set_ylabel('Kurtosis')
    ax2.set_xlabel('Time (years)')
    ax2.set_title(f'{variable} — Kurtosis over time')
    ax2.grid(True, alpha=0.3)

    # legend (one per ensemble) on top panel
    handles, labels = ax0.get_legend_handles_labels()
    if handles:
        ax0.legend(handles, labels, loc='best')

    plt.tight_layout()
    return fig


def plot_combined_figure(time_grid, data_matrix, display_names, variable, unit_str):
    """Create a single figure with a large time-series panel on the left
    and the three diagnostic panels stacked on the right.
    """
    # overall figure: left big panel, right column with 3 stacked panels
    # make left and right columns equal width so right diagnostics have more room
    fig = plt.figure(figsize=(12, 9))
    gs = fig.add_gridspec(1, 2, width_ratios=[1, 1], wspace=0.25)
    ax_ts = fig.add_subplot(gs[0, 0])
    right_gs = gs[0, 1].subgridspec(3, 1, hspace=0.35)
    ax0 = fig.add_subplot(right_gs[0, 0])
    ax1 = fig.add_subplot(right_gs[1, 0])
    ax2 = fig.add_subplot(right_gs[2, 0])

    # build ensemble map from display names ENSEMBLE:EXP
    ensemble_map = {}
    for idx, dn in enumerate(display_names):
        ens = dn.split(':', 1)[0]
        ensemble_map.setdefault(ens, []).append(idx)

    # palette (prefer external mapping if provided)
    palette = {}
    ens_names = list(ensemble_map.keys())
    external = globals().get('ensemble_to_base_color', None)
    if external:
        for ens in ens_names:
            palette[ens] = external.get(ens, plt.cm.tab10(0))
    else:
        base = plt.cm.tab10(np.linspace(0, 1, max(1, len(ens_names))))
        for i, ens in enumerate(ens_names):
            palette[ens] = base[i % base.shape[0]]

    # Plotting: left time-series with min-max faint band + IQR + dashed mean
    legend_handles = []
    legend_labels = []
    for ens, indices in ensemble_map.items():
        subset = data_matrix[indices, :]
        if subset.size == 0:
            continue
        with np.errstate(invalid='ignore'):
            pmin = np.nanmin(subset, axis=0)
            pmax = np.nanmax(subset, axis=0)
            p25 = np.nanpercentile(subset, 25, axis=0)
            p75 = np.nanpercentile(subset, 75, axis=0)
            mean_ts = np.nanmean(subset, axis=0)

        base_color = palette.get(ens)
        ax_ts.fill_between(time_grid, pmin, pmax, color=base_color, alpha=0.08)
        ax_ts.fill_between(time_grid, p25, p75, color=base_color, alpha=0.2)
        ax_ts.plot(time_grid, mean_ts, color=base_color, linewidth=1.5, linestyle='--')

        from matplotlib.lines import Line2D
        legend_handles.append(Line2D([0], [0], color=base_color, lw=3))
        legend_labels.append(f"{ens} (n={len(indices)})")

    if legend_handles:
        ax_ts.legend(legend_handles, legend_labels, loc='best')
    ax_ts.set_xlabel('Time (years)')
    ax_ts.set_ylabel(f'{variable}{unit_str}')
    ax_ts.grid(True, alpha=0.3)

    # Right column diagnostics: reuse computations and palette
    tiny = 1e-12
    for ens, indices in ensemble_map.items():
        subset = data_matrix[indices, :]
        if subset.size == 0:
            continue
        with np.errstate(invalid='ignore', divide='ignore'):
            mean = np.nanmean(subset, axis=0)
            pmin = np.nanmin(subset, axis=0)
            pmax = np.nanmax(subset, axis=0)
            spread = pmax - pmin
            mean_abs = np.abs(mean)
            mean_safe = mean_abs.copy()
            mean_safe[mean_safe < tiny] = np.nan
            ratio = spread / mean_safe
            std_ts = np.nanstd(subset, axis=0)
            kurt_ts = stats.kurtosis(subset, axis=0, nan_policy='omit')

        base_color = palette.get(ens)
        ax0.plot(time_grid, std_ts, '-', color=base_color, linewidth=1.5, label=f"{ens} (n={len(indices)})")
        ax1.plot(time_grid, ratio, '-', color=base_color, linewidth=1.5)
        ax2.plot(time_grid, kurt_ts, '-', color=base_color, linewidth=1.5)

    ax0.set_ylabel('Standard Deviation (σ)')
    ax0.set_title(f'Ensemble standard deviation (σ) for {variable}')
    ax0.grid(True, alpha=0.3)

    ax1.set_ylabel('Std / |Mean|')
    ax1.set_yscale('log')
    # shorter title while retaining intent: ratio of spread to mean (log scale)
    ax1.set_title('σ / |Mean| (log y-axis)')
    ax1.grid(True, alpha=0.3)

    ax2.set_ylabel('Kurtosis')
    ax2.set_xlabel('Time (years)')
    ax2.set_title(f'{variable} — Kurtosis over time')
    ax2.grid(True, alpha=0.3)

    handles, labels = ax0.get_legend_handles_labels()
    if handles:
        ax0.legend(handles, labels, loc='best')

    fig.tight_layout()
    return fig


def main():
    opts = parse_arguments()

    files, names = build_experiment_lists(opts)

    # Parse --ensemble-colors into a global mapping `ensemble_to_base_color`
    # so plotting functions can pick the colors per ensemble base.
    if getattr(opts, 'ensemble_colors', None):
        raw_colors = [c.strip() for c in opts.ensemble_colors.split(',') if c.strip()]
        # derive ensemble order from the display names (ENSEMBLE:EXP) in the files list
        ens_names = []
        for dn in names:
            ens = dn.split(':', 1)[0]
            if ens not in ens_names:
                ens_names.append(ens)

        # prefer ordering from --base if provided, otherwise use encountered order
        ensemble_order = []
        if getattr(opts, 'bases', None):
            try:
                base_list = [b.strip() for b in opts.bases.split(',') if b.strip()]
                for b in base_list:
                    if b in ens_names and b not in ensemble_order:
                        ensemble_order.append(b)
            except Exception:
                pass
        # append any ensembles not covered by -b
        for e in ens_names:
            if e not in ensemble_order:
                ensemble_order.append(e)

        ensemble_to_base_color = {}
        if len(raw_colors) == 0:
            pass
        else:
            for i, ens in enumerate(ensemble_order):
                ensemble_to_base_color[ens] = raw_colors[i % len(raw_colors)]

        # publish global mapping for plotting functions
        globals()['ensemble_to_base_color'] = ensemble_to_base_color
        print(f"Using ensemble colors: {ensemble_to_base_color}")

    # Read first file to get region names if needed
    # Read region names: prefer an external region-names file if provided,
    # otherwise read from the first regionalStats file if it contains 'regionNames'.
    rNames = None
    if getattr(opts, 'region_names_file', None):
        rn_file = opts.region_names_file
        if not os.path.exists(rn_file):
            sys.exit(f"ERROR: region names file not found: {rn_file}")
        with Dataset(rn_file, 'r') as f:
            if 'regionNames' in f.variables:
                raw = f.variables['regionNames'][:]
                rNames = []
                for r in range(raw.shape[0]):
                    try:
                        this = raw[r, :].tobytes().decode('utf-8').strip()
                    except Exception:
                        this = ''.join([c.decode('utf-8') for c in raw[r, :]])
                    rNames.append(this)
            else:
                sys.exit(f"ERROR: 'regionNames' not found in {rn_file}")
    else:
        first = files[0]
        with Dataset(first, 'r') as f:
            if 'regionNames' in f.variables:
                raw = f.variables['regionNames'][:]
                rNames = []
                for r in range(raw.shape[0]):
                    try:
                        this = raw[r, :].tobytes().decode('utf-8').strip()
                    except Exception:
                        this = ''.join([c.decode('utf-8') for c in raw[r, :]])
                    rNames.append(this)
            else:
                rNames = None

    # Map raw region names to human-friendly labels where available
    rNames_display = None
    if rNames is not None:
        # Build a cleaned alphanumeric key for each region name (similar to other scripts)
        rNamesOrig = [ ''.join(filter(str.isalnum, rn)) for rn in rNames ]

        # ISMIP6 basin mapping (Paolo 2023 update)
        ISMIP6basinInfo = {
            'ISMIP6BasinAAp': {'name': 'Dronning Maud Land', 'input': [60,9], 'outflow': [60,7], 'net': [0, 11], 'shelfMelt': [37.49]},
            'ISMIP6BasinApB': {'name': 'Enderby Land', 'input': [39,5], 'outflow': [40,2], 'net': [-1,5], 'shelfMelt': [17.34]},
            'ISMIP6BasinBC': {'name': 'Amery-Lambert', 'input': [73, 10], 'outflow': [77,4], 'net': [-4, 11], 'shelfMelt': [21.03]},
            'ISMIP6BasinCCp': {'name': 'Phillipi, Denman', 'input': [81, 13], 'outflow': [87,7], 'net':[-7,15], 'shelfMelt': [40.27]},
            'ISMIP6BasinCpD': {'name': 'Totten', 'input': [198,37], 'outflow': [207,13], 'net': [-8,39], 'shelfMelt': [69.88]},
            'ISMIP6BasinDDp': {'name': 'Mertz', 'input': [93,14], 'outflow': [94,6], 'net': [-2,16], 'shelfMelt': [17.72]},
            'ISMIP6BasinDpE': {'name': 'Victoria Land', 'input': [20,1], 'outflow': [22,3], 'net': [-2,4], 'shelfMelt': [11.32]},
            'ISMIP6BasinEF': {'name': 'Ross', 'input': [61+110,(10**2+7**2)**0.5], 'outflow': [49+80,(4**2+2**2)**0.5], 'net': [11+31,(11*2+7**2)**0.5], 'shelfMelt': [40.1]},
            'ISMIP6BasinFG': {'name': 'Getz', 'input': [108,28], 'outflow': [128,18], 'net': [-19,33], 'shelfMelt': [119.3]},
            'ISMIP6BasinGH': {'name': 'Thwaites/PIG', 'input': [177,25], 'outflow': [237,4], 'net': [-61,26], 'shelfMelt': [191.04]},
            'ISMIP6BasinHHp': {'name': 'Bellingshausen', 'input': [51,16], 'outflow': [86,10], 'net': [-35,19], 'shelfMelt': [54.57]},
            'ISMIP6BasinHpI': {'name': 'George VI', 'input': [71,21], 'outflow': [78,7], 'net': [-7,23], 'shelfMelt': [85.53]},
            'ISMIP6BasinIIpp': {'name': 'Larsen A-C', 'input': [15,5], 'outflow': [20,3], 'net': [-5,6], 'shelfMelt': [23.09]},
            'ISMIP6BasinIppJ': {'name': 'Larsen E', 'input': [8,4], 'outflow': [9,2], 'net': [-1,4], 'shelfMelt': [16.51]},
            'ISMIP6BasinJK': {'name': 'FRIS', 'input': [93+142, (8**2+11**2)**0.5], 'outflow': [75+145,(4**2+7**2)**0.5], 'net': [18-4,(9**2+13**2)**0.5], 'shelfMelt': [54.21]},
            'ISMIP6BasinKA': {'name': 'Brunt-Stancomb', 'input': [42+26,(8**2+7**2)**0.5], 'outflow': [45+28,(4**2+2**2)**0.5], 'net':[-3-1,(9**2+8**2)**0.5], 'shelfMelt': [26.05]}
        }

        rNames_display = []
        for key, raw in zip(rNamesOrig, rNames):
            if key in ISMIP6basinInfo:
                rNames_display.append(ISMIP6basinInfo[key]['name'])
            else:
                rNames_display.append(raw)

    # determine change mode
    change_mode = 'absolute' if opts.plotChange else None

    # determine list of region indices to process
    region_list = []
    if opts.region_indices:
        try:
            region_list = parse_region_indices(opts.region_indices)
        except Exception as e:
            sys.exit(f"ERROR parsing --region-indices: {e}")
    else:
        # single region via index (which may be a list/range string), or via name
        if opts.region_index is not None:
            try:
                region_list = parse_region_indices(opts.region_index)
            except Exception as e:
                sys.exit(f"ERROR parsing --region-index: {e}")
        elif opts.region_name is not None:
            if rNames is None:
                sys.exit('ERROR: region names not available in files; use --region-index instead')
            matches = [i for i, rn in enumerate(rNames) if opts.region_name in rn]
            if not matches:
                # try exact match
                try:
                    idx = rNames.index(opts.region_name)
                    region_list = [idx]
                except ValueError:
                    sys.exit(f"ERROR: region name '{opts.region_name}' not found")
            else:
                region_list = [matches[0]]
        else:
            sys.exit('ERROR: must provide --region-index, --region-name, or --region-indices')

    # Build unit string simply as empty (regional units handled by caller)
    unit_str = ''

    figs_to_show = []

    for region_idx in region_list:
        try:
            time_grid, data_matrix = build_time_grid_and_matrix(files, opts.variable, region_idx, change_mode)
        except Exception as e:
            print(f"Warning: failed to build time grid for region {region_idx}: {e}", file=sys.stderr)
            continue
        if time_grid.size == 0 or data_matrix.size == 0:
            print(f"Warning: no time-series data available for region {region_idx}", file=sys.stderr)
            continue

        # Drop the first time slice (index 0) to avoid anomalous initial values.
        # If there's only one or zero time points, skip plotting for this region.
        if time_grid.size <= 1:
            print(f"Warning: region {region_idx} has <=1 timepoints; skipping after drop-first policy", file=sys.stderr)
            continue
        time_grid = time_grid[1:]
        data_matrix = data_matrix[:, 1:]

        # Try to get a human-readable region name if available
        region_name_clean = ''
        region_display = ''
        if rNames_display is not None and 0 <= region_idx < len(rNames_display):
            region_display = rNames_display[region_idx]
            region_name_clean = sanitize_name(region_display)
        elif rNames is not None and 0 <= region_idx < len(rNames):
            region_display = rNames[region_idx]
            region_name_clean = sanitize_name(region_display)

        # Apply unit scaling for volume-like variables
        scale = get_scale_factor(opts.units) if hasattr(opts, 'units') else get_scale_factor('Gt')
        unit_str = get_unit_string(opts.variable, opts.units)
        try:
            # scale in-place; ignore non-numeric entries
            with np.errstate(invalid='ignore'):
                data_matrix = data_matrix * scale
        except Exception:
            pass

        # Create single combined figure with time-series on the left and diagnostics
        # stacked on the right.
        fig_combined = plot_combined_figure(time_grid, data_matrix, names, opts.variable, unit_str)

        # If a human-readable region name is available, include it as the figure suptitle
        if region_display:
            try:
                fig_combined.suptitle(f"{region_display} — {opts.variable}", y=0.96, fontsize=12)
            except Exception:
                pass

        # Reserve space for suptitle to avoid overlap
        try:
            fig_combined.tight_layout(rect=[0, 0, 1, 0.93])
        except Exception:
            try:
                fig_combined.subplots_adjust(top=0.93)
            except Exception:
                pass

        if opts.savebase:
            base = opts.savebase.replace('.png', '')
            suffix = f"_region{region_idx}"
            if region_name_clean:
                suffix += f"_{region_name_clean}"
            out_name = base + suffix + '_regional_combined.png'
            fig_combined.savefig(out_name, dpi=300, bbox_inches='tight')
            print(f"Saved: {out_name}")
        else:
            figs_to_show.append(fig_combined)

    # display all figures at once (no pause between regions)
    if not opts.savebase and figs_to_show:
        plt.show()


if __name__ == '__main__':
    main()
